# Generated by Django 3.2.25 on 2025-04-22 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_module', '0002_auto_20250422_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_module.student')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comment', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.article')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_module.proff')),
            ],
            options={
                'unique_together': {('article', 'professor')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='professors',
            field=models.ManyToManyField(through='article_module.ArticleScore', to='account_module.Proff'),
        ),
    ]
