# Generated by Django 3.2.25 on 2025-05-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescore',
            name='student_protest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
