# Generated by Django 3.2.25 on 2025-05-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_auto_20250505_1209'),
        ('article_module', '0005_auto_20250505_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edit_permission',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_manager', to='account_module.proff'),
        ),
        migrations.AddField(
            model_name='articlescore',
            name='scoring_permission',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='professors',
            field=models.ManyToManyField(related_name='article_professors', through='article_module.ArticleScore', to='account_module.Proff'),
        ),
    ]
