# Generated by Django 3.2.25 on 2025-04-22 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_num', models.IntegerField(blank=True, null=True)),
                ('faculty', models.CharField(choices=[('computer_engineering', 'Computer Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('math', 'Math'), ('mechanic_engineering', 'Mechanical Engineering')], max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentProfessorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('advisor', 'Advisor'), ('manager', 'Manager'), ('referee', 'Referee')], max_length=50)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_module.proff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_module.student')),
            ],
            options={
                'unique_together': {('student', 'professor', 'role')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='prof',
            field=models.ManyToManyField(blank=True, through='account_module.StudentProfessorRelation', to='account_module.Proff'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
