# Generated by Django 3.2.25 on 2025-04-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_auto_20250422_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_professor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('proff', 'Professor'), ('student', 'student')], max_length=100, null=True),
        ),
    ]
