# Generated by Django 3.2.25 on 2025-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='prof',
        ),
        migrations.AddField(
            model_name='student',
            name='education_level',
            field=models.CharField(choices=[('phd', 'PhD'), ('post_gradual', 'Post Gradual')], default='post_gradual', max_length=100),
        ),
        migrations.DeleteModel(
            name='StudentProfessorRelation',
        ),
    ]
