# Generated by Django 3.2.25 on 2025-05-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_auto_20250505_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='proff',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proff',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
