# Generated by Django 3.2.25 on 2025-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_auto_20250513_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proff',
            name='education_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proff',
            name='field_of_study',
            field=models.CharField(max_length=100),
        ),
    ]
